# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/daml/ledger/api/v2/trace_context.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*com/daml/ledger/api/v2/trace_context.proto\x12\x16\x63om.daml.ledger.api.v2\"`\n\x0cTraceContext\x12\x18\n\x0btraceparent\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\ntracestate\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_traceparentB\r\n\x0b_tracestateBI\n\x16\x63om.daml.ledger.api.v2B\x16TraceContextOuterClass\xaa\x02\x16\x43om.Daml.Ledger.Api.V2b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.daml.ledger.api.v2.trace_context_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.daml.ledger.api.v2B\026TraceContextOuterClass\252\002\026Com.Daml.Ledger.Api.V2'
  _TRACECONTEXT._serialized_start=70
  _TRACECONTEXT._serialized_end=166
# @@protoc_insertion_point(module_scope)
