/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "com/daml/ledger/api/v2/transaction.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_daml_ledger_api_v2_TreeEvent, com_daml_ledger_api_v2_TreeEvent, 4)

PB_BIND(com_daml_ledger_api_v2_TransactionTree, com_daml_ledger_api_v2_TransactionTree, 2)

PB_BIND(com_daml_ledger_api_v2_TransactionTree_EventsByIdEntry,
        com_daml_ledger_api_v2_TransactionTree_EventsByIdEntry,
        4)

PB_BIND(com_daml_ledger_api_v2_Transaction, com_daml_ledger_api_v2_Transaction, 2)
