/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_PACKAGE_REFERENCE_PB_H_INCLUDED
#define PB_COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_PACKAGE_REFERENCE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _com_daml_ledger_api_v2_PackageReference {
    /* Required */
    char package_id[1024];
    /* Required */
    char package_name[1024];
    /* Required */
    char package_version[1024];
} com_daml_ledger_api_v2_PackageReference;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_daml_ledger_api_v2_PackageReference_init_default {"", "", ""}
#define com_daml_ledger_api_v2_PackageReference_init_zero {"", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define com_daml_ledger_api_v2_PackageReference_package_id_tag 1
#define com_daml_ledger_api_v2_PackageReference_package_name_tag 2
#define com_daml_ledger_api_v2_PackageReference_package_version_tag 3

/* Struct field encoding specification for nanopb */
#define com_daml_ledger_api_v2_PackageReference_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   package_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   package_name,      2) \
X(a, STATIC,   SINGULAR, STRING,   package_version,   3)
#define com_daml_ledger_api_v2_PackageReference_CALLBACK NULL
#define com_daml_ledger_api_v2_PackageReference_DEFAULT NULL

extern const pb_msgdesc_t com_daml_ledger_api_v2_PackageReference_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_daml_ledger_api_v2_PackageReference_fields &com_daml_ledger_api_v2_PackageReference_msg

/* Maximum encoded size of messages (where known) */
#define COM_DAML_LEDGER_API_V2_COM_DAML_LEDGER_API_V2_PACKAGE_REFERENCE_PB_H_MAX_SIZE com_daml_ledger_api_v2_PackageReference_size
#define com_daml_ledger_api_v2_PackageReference_size 3078

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
