/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_COM_DAML_LEDGER_API_V2_INTERACTIVE_COM_DAML_LEDGER_API_V2_INTERACTIVE_INTERACTIVE_SUBMISSION_SERVICE_PB_H_INCLUDED
#define PB_COM_DAML_LEDGER_API_V2_INTERACTIVE_COM_DAML_LEDGER_API_V2_INTERACTIVE_INTERACTIVE_SUBMISSION_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "com/daml/ledger/api/v2/commands.pb.h"
#include "com/daml/ledger/api/v2/interactive/interactive_submission_common_data.pb.h"
#include "com/daml/ledger/api/v2/interactive/transaction/v1/interactive_submission_data.pb.h"
#include "com/daml/ledger/api/v2/package_reference.pb.h"
#include "com/daml/ledger/api/v2/value.pb.h"
#include "google/protobuf/duration.pb.h"
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* [docs-entry-start: HashingSchemeVersion]
 The hashing scheme version used when building the hash of the PreparedTransaction */
typedef enum _com_daml_ledger_api_v2_interactive_HashingSchemeVersion { 
    com_daml_ledger_api_v2_interactive_HashingSchemeVersion_HASHING_SCHEME_VERSION_UNSPECIFIED = 0, 
    com_daml_ledger_api_v2_interactive_HashingSchemeVersion_HASHING_SCHEME_VERSION_V2 = 2 
} com_daml_ledger_api_v2_interactive_HashingSchemeVersion;

typedef enum _com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec { 
    com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_UNSPECIFIED = 0, 
    /* EdDSA Signature based on Curve25519 with SHA-512
 http://ed25519.cr.yp.to/ */
    com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_ED25519 = 1, 
    /* Elliptic Curve Digital Signature Algorithm with SHA256 */
    com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_256 = 2, 
    /* Elliptic Curve Digital Signature Algorithm with SHA384 */
    com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384 = 3 
} com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec;

typedef enum _com_daml_ledger_api_v2_interactive_SignatureFormat { 
    com_daml_ledger_api_v2_interactive_SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED = 0, 
    /* Signature scheme specific signature format
 Legacy format no longer used, except for migrations */
    com_daml_ledger_api_v2_interactive_SignatureFormat_SIGNATURE_FORMAT_RAW = 1, 
    /* ASN.1 + DER-encoding of the `r` and `s` integers, as defined in https://datatracker.ietf.org/doc/html/rfc3279#section-2.2.3
 Used for ECDSA signatures */
    com_daml_ledger_api_v2_interactive_SignatureFormat_SIGNATURE_FORMAT_DER = 2, 
    /* Concatenation of the integers `r || s` in little-endian form, as defined in https://datatracker.ietf.org/doc/html/rfc8032#section-3.3
 Note that this is different from the format defined in IEEE P1363, which uses concatenation in big-endian form.
 Used for EdDSA signatures */
    com_daml_ledger_api_v2_interactive_SignatureFormat_SIGNATURE_FORMAT_CONCAT = 3, 
    /* Symbolic crypto, must only be used for testing */
    com_daml_ledger_api_v2_interactive_SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC = 10000 
} com_daml_ledger_api_v2_interactive_SignatureFormat;

/* Struct definitions */
typedef struct _com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse { 
    char dummy_field;
} com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse;

/* Additional signatures provided by the submitting parties */
typedef struct _com_daml_ledger_api_v2_interactive_PartySignatures { 
    /* Additional signatures provided by all individual parties */
    pb_callback_t signatures; 
} com_daml_ledger_api_v2_interactive_PartySignatures;

typedef struct _com_daml_ledger_api_v2_interactive_DamlTransaction { 
    /* The package reference of the preferred package.
 Required */
    char version[1024]; 
    /* The synchronizer for which the preferred package was computed.
 If the synchronizer_id was specified in the request, then it matches the request synchronizer_id.
 Required */
    pb_callback_t roots; 
    pb_callback_t nodes; 
    pb_callback_t node_seeds; 
} com_daml_ledger_api_v2_interactive_DamlTransaction;

typedef struct _com_daml_ledger_api_v2_interactive_DamlTransaction_Node { 
    char node_id[1024]; 
    pb_size_t which_versioned_node;
    union {
        com_daml_ledger_api_v2_interactive_transaction_v1_Node v1;
    }; 
} com_daml_ledger_api_v2_interactive_DamlTransaction_Node;

typedef PB_BYTES_ARRAY_T(1024) com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_seed_t;
typedef struct _com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed { 
    int32_t node_id; 
    com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_seed_t seed; 
} com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed;

typedef struct _com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest { 
    pb_callback_t parties; 
    char package_name[1024]; 
    char synchronizer_id[1024]; 
    bool has_vetting_valid_at;
    google_protobuf_Timestamp vetting_valid_at; 
} com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest;

typedef struct _com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry { 
    /* The parties whose participants' vetting state should be considered when resolving the preferred package.
 Required */
    bool has_key;
    com_daml_ledger_api_v2_interactive_GlobalKey key; 
    /* The package-name for which the preferred package should be resolved.
 Required */
    bool has_value;
    com_daml_ledger_api_v2_Value value; 
} com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry;

typedef PB_BYTES_ARRAY_T(1024) com_daml_ledger_api_v2_interactive_Metadata_InputContract_driver_metadata_t;
typedef struct _com_daml_ledger_api_v2_interactive_Metadata_InputContract { 
    /* Not populated when no preferred package is found
 Optional */
    pb_size_t which_contract;
    union {
        com_daml_ledger_api_v2_interactive_transaction_v1_Create v1;
    }; 
    uint64_t created_at; 
    com_daml_ledger_api_v2_interactive_Metadata_InputContract_driver_metadata_t driver_metadata; 
} com_daml_ledger_api_v2_interactive_Metadata_InputContract;

/* Daml Transaction.
 This represents the effect on the ledger if this transaction is successfully committed. */
typedef struct _com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo { 
    /* Transaction version, will be >= max(nodes version) */
    pb_callback_t act_as; 
    /* Root nodes of the transaction */
    char command_id[1024]; 
} com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo;

typedef struct _com_daml_ledger_api_v2_interactive_MinLedgerTime { 
    /* Lower bound for the ledger time assigned to the resulting transaction.
 The ledger time of a transaction is assigned as part of command interpretation.
 Important note: for interactive submissions, if the transaction depends on time, it **must** be signed
 and submitted within a time window around the ledger time assigned to the transaction during the prepare method.
 The time delta around that ledger time is a configuration of the ledger, usually short, around 1 minute.
 If however the transaction does not depend on time, the available time window to sign and submit the transaction is bound
 by the submission timestamp, which is also assigned in the "prepare" step (this request),
 but can be configured with a much larger skew, allowing for more time to sign the request (in the order of hours).
 Must not be set at the same time as min_ledger_time_rel.
 Optional */
    pb_size_t which_time;
    union {
        google_protobuf_Timestamp min_ledger_time_abs;
        google_protobuf_Duration min_ledger_time_rel;
    }; 
} com_daml_ledger_api_v2_interactive_MinLedgerTime;

typedef struct _com_daml_ledger_api_v2_interactive_PackagePreference { 
    bool has_package_reference;
    com_daml_ledger_api_v2_PackageReference package_reference; 
    char synchronizer_id[1024]; 
} com_daml_ledger_api_v2_interactive_PackagePreference;

typedef PB_BYTES_ARRAY_T(1024) com_daml_ledger_api_v2_interactive_Signature_signature_t;
typedef struct _com_daml_ledger_api_v2_interactive_Signature { 
    com_daml_ledger_api_v2_interactive_SignatureFormat format; 
    com_daml_ledger_api_v2_interactive_Signature_signature_t signature; 
    /* The fingerprint/id of the keypair used to create this signature and needed to verify. */
    char signed_by[1024]; 
    /* The signing algorithm specification used to produce this signature */
    com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec signing_algorithm_spec; 
} com_daml_ledger_api_v2_interactive_Signature;

/* Signatures provided by a single party */
typedef struct _com_daml_ledger_api_v2_interactive_SinglePartySignatures { 
    char party[1024]; /* Submitting party */
    pb_callback_t signatures; /* Signatures */
} com_daml_ledger_api_v2_interactive_SinglePartySignatures;

typedef struct _com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse { 
    bool has_package_preference;
    com_daml_ledger_api_v2_interactive_PackagePreference package_preference; 
} com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse;

/* Transaction Metadata
 Refer to the hashing documentation for information on how it should be hashed. */
typedef struct _com_daml_ledger_api_v2_interactive_Metadata { 
    bool has_submitter_info;
    com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo submitter_info; 
    char synchronizer_id[1024]; 
    uint32_t mediator_group; 
    char transaction_uuid[1024]; 
    uint64_t submission_time; 
    pb_callback_t input_contracts; 
    /* Where ledger time constraints are imposed during the execution of the contract they will be populated
 in the fields below. These are optional because if the transaction does NOT depend on time, these values
 do not need to be set.
 The final ledger effective time used will be chosen when the command is submitted through the [execute] RPC.
 If the ledger effective time is outside of any populated min/max bounds then a different transaction
 can result, that will cause a confirmation message rejection. */
    pb_callback_t global_key_mapping; 
    bool has_min_ledger_effective_time;
    uint64_t min_ledger_effective_time; 
    /* Contextual information needed to process the transaction but not signed, either because it's already indirectly
 signed by signing the transaction, or because it doesn't impact the ledger state */
    bool has_max_ledger_effective_time;
    uint64_t max_ledger_effective_time; 
} com_daml_ledger_api_v2_interactive_Metadata;

typedef struct _com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest { 
    /* Uniquely identifies the participant user that prepares the transaction.
 Must be a valid UserIdString (as described in ``value.proto``).
 Required unless authentication is used with a user token.
 In that case, the token's user-id will be used for the request's user_id. */
    char user_id[1024]; 
    /* Uniquely identifies the command.
 The triple (user_id, act_as, command_id) constitutes the change ID for the intended ledger change,
 where act_as is interpreted as a set of party names.
 The change ID can be used for matching the intended ledger changes with all their completions.
 Must be a valid LedgerString (as described in ``value.proto``).
 Required */
    char command_id[1024]; 
    /* Individual elements of this atomic command. Must be non-empty.
 Required */
    pb_callback_t commands; 
    /* Optional */
    bool has_min_ledger_time;
    com_daml_ledger_api_v2_interactive_MinLedgerTime min_ledger_time; 
    /* Set of parties on whose behalf the command should be executed, if submitted.
 If ledger API authorization is enabled, then the authorization metadata must authorize the sender of the request
 to **read** (not act) on behalf of each of the given parties. This is because this RPC merely prepares a transaction
 and does not execute it. Therefore read authorization is sufficient even for actAs parties.
 Note: This may change, and more specific authorization scope may be introduced in the future.
 Each element must be a valid PartyIdString (as described in ``value.proto``).
 Required, must be non-empty. */
    pb_callback_t act_as; 
    /* Set of parties on whose behalf (in addition to all parties listed in ``act_as``) contracts can be retrieved.
 This affects Daml operations such as ``fetch``, ``fetchByKey``, ``lookupByKey``, ``exercise``, and ``exerciseByKey``.
 Note: A command can only use contracts that are visible to at least
 one of the parties in ``act_as`` or ``read_as``. This visibility check is independent from the Daml authorization
 rules for fetch operations.
 If ledger API authorization is enabled, then the authorization metadata must authorize the sender of the request
 to read contract data on behalf of each of the given parties.
 Optional */
    pb_callback_t read_as; 
    /* Additional contracts used to resolve contract & contract key lookups.
 Optional */
    pb_callback_t disclosed_contracts; 
    /* Must be a valid synchronizer id
 Required */
    char synchronizer_id[1024]; 
    /* The package-id selection preference of the client for resolving
 package names and interface instances in command submission and interpretation */
    pb_callback_t package_id_selection_preference; 
    /* When true, the response will contain additional details on how the transaction was encoded and hashed
 This can be useful for troubleshooting of hash mismatches. Should only be used for debugging. */
    bool verbose_hashing; 
    /* Fetches the contract keys into the caches to speed up the command processing.
 Should only contain contract keys that are expected to be resolved during interpretation of the commands.
 Keys of disclosed contracts do not need prefetching.

 Optional */
    pb_callback_t prefetch_contract_keys; 
} com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest;

/* *
 Prepared Transaction Message */
typedef struct _com_daml_ledger_api_v2_interactive_PreparedTransaction { 
    /* Daml Transaction representing the ledger effect if executed. See below */
    bool has_transaction;
    com_daml_ledger_api_v2_interactive_DamlTransaction transaction; 
    /* Metadata context necessary to execute the transaction */
    bool has_metadata;
    com_daml_ledger_api_v2_interactive_Metadata metadata; 
} com_daml_ledger_api_v2_interactive_PreparedTransaction;

typedef struct _com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest { 
    /* the prepared transaction
 Typically this is the value of the `prepared_transaction` field in `PrepareSubmissionResponse`
 obtained from calling `prepareSubmission`. */
    bool has_prepared_transaction;
    com_daml_ledger_api_v2_interactive_PreparedTransaction prepared_transaction; 
    /* The party(ies) signatures that authorize the prepared submission to be executed by this node.
 Each party can provide one or more signatures..
 and one or more parties can sign.
 Note that currently, only single party submissions are supported. */
    bool has_party_signatures;
    com_daml_ledger_api_v2_interactive_PartySignatures party_signatures; 
    /* Specifies the length of the deduplication period.
 It is interpreted relative to the local clock at some point during the submission's processing.
 Must be non-negative. Must not exceed the maximum deduplication time. */
    pb_size_t which_deduplication_period;
    union {
        google_protobuf_Duration deduplication_duration;
        int64_t deduplication_offset;
    }; 
    /* Specifies the start of the deduplication period by a completion stream offset (exclusive).
 Must be a valid absolute offset (positive integer). */
    char *submission_id; 
    /* A unique identifier to distinguish completions for different submissions with the same change ID.
 Typically a random UUID. Applications are expected to use a different UUID for each retry of a submission
 with the same change ID.
 Must be a valid LedgerString (as described in ``value.proto``).

 Required */
    char *user_id; 
    /* See [PrepareSubmissionRequest.user_id] */
    com_daml_ledger_api_v2_interactive_HashingSchemeVersion hashing_scheme_version; 
    /* The hashing scheme version used when building the hash */
    bool has_min_ledger_time;
    com_daml_ledger_api_v2_interactive_MinLedgerTime min_ledger_time; 
} com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest;

typedef PB_BYTES_ARRAY_T(32) com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_prepared_transaction_hash_t;
typedef struct _com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse { 
    /* The interpreted transaction, it represents the ledger changes necessary to execute the commands specified in the request.
 Clients MUST display the content of the transaction to the user for them to validate before signing the hash if the preparing participant is not trusted. */
    bool has_prepared_transaction;
    com_daml_ledger_api_v2_interactive_PreparedTransaction prepared_transaction; 
    /* Hash of the transaction, this is what needs to be signed by the party to authorize the transaction.
 Only provided for convenience, clients MUST recompute the hash from the raw transaction if the preparing participant is not trusted.
 May be removed in future versions */
    com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_prepared_transaction_hash_t prepared_transaction_hash; 
    /* The hashing scheme version used when building the hash */
    com_daml_ledger_api_v2_interactive_HashingSchemeVersion hashing_scheme_version; 
    /* Optional additional details on how the transaction was encoded and hashed. Only set if verbose_hashing = true in the request
 Note that there are no guarantees on the stability of the format or content of this field.
 Its content should NOT be parsed and should only be used for troubleshooting purposes. */
    char *hashing_details; 
} com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse;


/* Helper constants for enums */
#define _com_daml_ledger_api_v2_interactive_HashingSchemeVersion_MIN com_daml_ledger_api_v2_interactive_HashingSchemeVersion_HASHING_SCHEME_VERSION_UNSPECIFIED
#define _com_daml_ledger_api_v2_interactive_HashingSchemeVersion_MAX com_daml_ledger_api_v2_interactive_HashingSchemeVersion_HASHING_SCHEME_VERSION_V2
#define _com_daml_ledger_api_v2_interactive_HashingSchemeVersion_ARRAYSIZE ((com_daml_ledger_api_v2_interactive_HashingSchemeVersion)(com_daml_ledger_api_v2_interactive_HashingSchemeVersion_HASHING_SCHEME_VERSION_V2+1))

#define _com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_MIN com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_UNSPECIFIED
#define _com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_MAX com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384
#define _com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_ARRAYSIZE ((com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec)(com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384+1))

#define _com_daml_ledger_api_v2_interactive_SignatureFormat_MIN com_daml_ledger_api_v2_interactive_SignatureFormat_SIGNATURE_FORMAT_UNSPECIFIED
#define _com_daml_ledger_api_v2_interactive_SignatureFormat_MAX com_daml_ledger_api_v2_interactive_SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC
#define _com_daml_ledger_api_v2_interactive_SignatureFormat_ARRAYSIZE ((com_daml_ledger_api_v2_interactive_SignatureFormat)(com_daml_ledger_api_v2_interactive_SignatureFormat_SIGNATURE_FORMAT_SYMBOLIC+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_init_default {"", "", {{NULL}, NULL}, false, com_daml_ledger_api_v2_interactive_MinLedgerTime_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, "", {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_init_default {false, com_daml_ledger_api_v2_interactive_PreparedTransaction_init_default, {0, {0}}, _com_daml_ledger_api_v2_interactive_HashingSchemeVersion_MIN, NULL}
#define com_daml_ledger_api_v2_interactive_Signature_init_default {_com_daml_ledger_api_v2_interactive_SignatureFormat_MIN, {0, {0}}, "", _com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_MIN}
#define com_daml_ledger_api_v2_interactive_SinglePartySignatures_init_default {"", {{NULL}, NULL}}
#define com_daml_ledger_api_v2_interactive_PartySignatures_init_default {{{NULL}, NULL}}
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_init_default {false, com_daml_ledger_api_v2_interactive_PreparedTransaction_init_default, false, com_daml_ledger_api_v2_interactive_PartySignatures_init_default, 0, {google_protobuf_Duration_init_default}, NULL, NULL, _com_daml_ledger_api_v2_interactive_HashingSchemeVersion_MIN, false, com_daml_ledger_api_v2_interactive_MinLedgerTime_init_default}
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse_init_default {0}
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_init_default {0, {google_protobuf_Timestamp_init_default}}
#define com_daml_ledger_api_v2_interactive_PreparedTransaction_init_default {false, com_daml_ledger_api_v2_interactive_DamlTransaction_init_default, false, com_daml_ledger_api_v2_interactive_Metadata_init_default}
#define com_daml_ledger_api_v2_interactive_Metadata_init_default {false, com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_init_default, "", 0, "", 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_init_default {{{NULL}, NULL}, ""}
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_init_default {false, com_daml_ledger_api_v2_interactive_GlobalKey_init_default, false, com_daml_ledger_api_v2_Value_init_default}
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_init_default {0, {com_daml_ledger_api_v2_interactive_transaction_v1_Create_init_default}, 0, {0, {0}}}
#define com_daml_ledger_api_v2_interactive_DamlTransaction_init_default {"", {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_init_default {0, {0, {0}}}
#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_init_default {"", 0, {com_daml_ledger_api_v2_interactive_transaction_v1_Node_init_default}}
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_init_default {{{NULL}, NULL}, "", "", false, google_protobuf_Timestamp_init_default}
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_init_default {false, com_daml_ledger_api_v2_interactive_PackagePreference_init_default}
#define com_daml_ledger_api_v2_interactive_PackagePreference_init_default {false, com_daml_ledger_api_v2_PackageReference_init_default, ""}
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_init_zero {"", "", {{NULL}, NULL}, false, com_daml_ledger_api_v2_interactive_MinLedgerTime_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, "", {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_init_zero {false, com_daml_ledger_api_v2_interactive_PreparedTransaction_init_zero, {0, {0}}, _com_daml_ledger_api_v2_interactive_HashingSchemeVersion_MIN, NULL}
#define com_daml_ledger_api_v2_interactive_Signature_init_zero {_com_daml_ledger_api_v2_interactive_SignatureFormat_MIN, {0, {0}}, "", _com_daml_ledger_api_v2_interactive_SigningAlgorithmSpec_MIN}
#define com_daml_ledger_api_v2_interactive_SinglePartySignatures_init_zero {"", {{NULL}, NULL}}
#define com_daml_ledger_api_v2_interactive_PartySignatures_init_zero {{{NULL}, NULL}}
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_init_zero {false, com_daml_ledger_api_v2_interactive_PreparedTransaction_init_zero, false, com_daml_ledger_api_v2_interactive_PartySignatures_init_zero, 0, {google_protobuf_Duration_init_zero}, NULL, NULL, _com_daml_ledger_api_v2_interactive_HashingSchemeVersion_MIN, false, com_daml_ledger_api_v2_interactive_MinLedgerTime_init_zero}
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse_init_zero {0}
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_init_zero {0, {google_protobuf_Timestamp_init_zero}}
#define com_daml_ledger_api_v2_interactive_PreparedTransaction_init_zero {false, com_daml_ledger_api_v2_interactive_DamlTransaction_init_zero, false, com_daml_ledger_api_v2_interactive_Metadata_init_zero}
#define com_daml_ledger_api_v2_interactive_Metadata_init_zero {false, com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_init_zero, "", 0, "", 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_init_zero {{{NULL}, NULL}, ""}
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_init_zero {false, com_daml_ledger_api_v2_interactive_GlobalKey_init_zero, false, com_daml_ledger_api_v2_Value_init_zero}
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_init_zero {0, {com_daml_ledger_api_v2_interactive_transaction_v1_Create_init_zero}, 0, {0, {0}}}
#define com_daml_ledger_api_v2_interactive_DamlTransaction_init_zero {"", {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_init_zero {0, {0, {0}}}
#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_init_zero {"", 0, {com_daml_ledger_api_v2_interactive_transaction_v1_Node_init_zero}}
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_init_zero {{{NULL}, NULL}, "", "", false, google_protobuf_Timestamp_init_zero}
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_init_zero {false, com_daml_ledger_api_v2_interactive_PackagePreference_init_zero}
#define com_daml_ledger_api_v2_interactive_PackagePreference_init_zero {false, com_daml_ledger_api_v2_PackageReference_init_zero, ""}

/* Field tags (for use in manual encoding/decoding) */
#define com_daml_ledger_api_v2_interactive_PartySignatures_signatures_tag 1
#define com_daml_ledger_api_v2_interactive_DamlTransaction_version_tag 1
#define com_daml_ledger_api_v2_interactive_DamlTransaction_roots_tag 2
#define com_daml_ledger_api_v2_interactive_DamlTransaction_nodes_tag 3
#define com_daml_ledger_api_v2_interactive_DamlTransaction_node_seeds_tag 4
#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_node_id_tag 1
#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_v1_tag 1000
#define com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_node_id_tag 1
#define com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_seed_tag 2
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_parties_tag 1
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_package_name_tag 2
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_synchronizer_id_tag 3
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_vetting_valid_at_tag 4
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_key_tag 1
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_value_tag 2
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_v1_tag 1
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_created_at_tag 1000
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_driver_metadata_tag 1001
#define com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_act_as_tag 1
#define com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_command_id_tag 2
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_min_ledger_time_abs_tag 1
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_min_ledger_time_rel_tag 2
#define com_daml_ledger_api_v2_interactive_PackagePreference_package_reference_tag 1
#define com_daml_ledger_api_v2_interactive_PackagePreference_synchronizer_id_tag 2
#define com_daml_ledger_api_v2_interactive_Signature_format_tag 1
#define com_daml_ledger_api_v2_interactive_Signature_signature_tag 2
#define com_daml_ledger_api_v2_interactive_Signature_signed_by_tag 3
#define com_daml_ledger_api_v2_interactive_Signature_signing_algorithm_spec_tag 4
#define com_daml_ledger_api_v2_interactive_SinglePartySignatures_party_tag 1
#define com_daml_ledger_api_v2_interactive_SinglePartySignatures_signatures_tag 2
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_package_preference_tag 1
#define com_daml_ledger_api_v2_interactive_Metadata_submitter_info_tag 2
#define com_daml_ledger_api_v2_interactive_Metadata_synchronizer_id_tag 3
#define com_daml_ledger_api_v2_interactive_Metadata_mediator_group_tag 4
#define com_daml_ledger_api_v2_interactive_Metadata_transaction_uuid_tag 5
#define com_daml_ledger_api_v2_interactive_Metadata_submission_time_tag 6
#define com_daml_ledger_api_v2_interactive_Metadata_input_contracts_tag 7
#define com_daml_ledger_api_v2_interactive_Metadata_global_key_mapping_tag 8
#define com_daml_ledger_api_v2_interactive_Metadata_min_ledger_effective_time_tag 9
#define com_daml_ledger_api_v2_interactive_Metadata_max_ledger_effective_time_tag 10
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_user_id_tag 1
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_command_id_tag 2
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_commands_tag 3
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_min_ledger_time_tag 4
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_act_as_tag 5
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_read_as_tag 6
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_disclosed_contracts_tag 7
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_synchronizer_id_tag 8
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_package_id_selection_preference_tag 9
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_verbose_hashing_tag 10
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_prefetch_contract_keys_tag 15
#define com_daml_ledger_api_v2_interactive_PreparedTransaction_transaction_tag 1
#define com_daml_ledger_api_v2_interactive_PreparedTransaction_metadata_tag 2
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_prepared_transaction_tag 1
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_party_signatures_tag 2
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_deduplication_duration_tag 3
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_deduplication_offset_tag 4
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_submission_id_tag 5
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_user_id_tag 6
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_hashing_scheme_version_tag 7
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_min_ledger_time_tag 8
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_prepared_transaction_tag 1
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_prepared_transaction_hash_tag 2
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_hashing_scheme_version_tag 3
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_hashing_details_tag 4

/* Struct field encoding specification for nanopb */
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   user_id,           1) \
X(a, STATIC,   SINGULAR, STRING,   command_id,        2) \
X(a, CALLBACK, REPEATED, MESSAGE,  commands,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  min_ledger_time,   4) \
X(a, CALLBACK, REPEATED, STRING,   act_as,            5) \
X(a, CALLBACK, REPEATED, STRING,   read_as,           6) \
X(a, CALLBACK, REPEATED, MESSAGE,  disclosed_contracts,   7) \
X(a, STATIC,   SINGULAR, STRING,   synchronizer_id,   8) \
X(a, CALLBACK, REPEATED, STRING,   package_id_selection_preference,   9) \
X(a, STATIC,   SINGULAR, BOOL,     verbose_hashing,  10) \
X(a, CALLBACK, REPEATED, MESSAGE,  prefetch_contract_keys,  15)
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_commands_MSGTYPE com_daml_ledger_api_v2_Command
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_min_ledger_time_MSGTYPE com_daml_ledger_api_v2_interactive_MinLedgerTime
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_disclosed_contracts_MSGTYPE com_daml_ledger_api_v2_DisclosedContract
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_prefetch_contract_keys_MSGTYPE com_daml_ledger_api_v2_PrefetchContractKey

#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  prepared_transaction,   1) \
X(a, STATIC,   SINGULAR, BYTES,    prepared_transaction_hash,   2) \
X(a, STATIC,   SINGULAR, UENUM,    hashing_scheme_version,   3) \
X(a, POINTER,  OPTIONAL, STRING,   hashing_details,   4)
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_prepared_transaction_MSGTYPE com_daml_ledger_api_v2_interactive_PreparedTransaction

#define com_daml_ledger_api_v2_interactive_Signature_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    format,            1) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         2) \
X(a, STATIC,   SINGULAR, STRING,   signed_by,         3) \
X(a, STATIC,   SINGULAR, UENUM,    signing_algorithm_spec,   4)
#define com_daml_ledger_api_v2_interactive_Signature_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_Signature_DEFAULT NULL

#define com_daml_ledger_api_v2_interactive_SinglePartySignatures_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   party,             1) \
X(a, CALLBACK, REPEATED, MESSAGE,  signatures,        2)
#define com_daml_ledger_api_v2_interactive_SinglePartySignatures_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_interactive_SinglePartySignatures_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_SinglePartySignatures_signatures_MSGTYPE com_daml_ledger_api_v2_interactive_Signature

#define com_daml_ledger_api_v2_interactive_PartySignatures_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  signatures,        1)
#define com_daml_ledger_api_v2_interactive_PartySignatures_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_interactive_PartySignatures_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_PartySignatures_signatures_MSGTYPE com_daml_ledger_api_v2_interactive_SinglePartySignatures

#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  prepared_transaction,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  party_signatures,   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (deduplication_period,deduplication_duration,deduplication_duration),   3) \
X(a, STATIC,   ONEOF,    INT64,    (deduplication_period,deduplication_offset,deduplication_offset),   4) \
X(a, POINTER,  SINGULAR, STRING,   submission_id,     5) \
X(a, POINTER,  SINGULAR, STRING,   user_id,           6) \
X(a, STATIC,   SINGULAR, UENUM,    hashing_scheme_version,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  min_ledger_time,   8)
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_prepared_transaction_MSGTYPE com_daml_ledger_api_v2_interactive_PreparedTransaction
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_party_signatures_MSGTYPE com_daml_ledger_api_v2_interactive_PartySignatures
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_deduplication_period_deduplication_duration_MSGTYPE google_protobuf_Duration
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_min_ledger_time_MSGTYPE com_daml_ledger_api_v2_interactive_MinLedgerTime

#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse_FIELDLIST(X, a) \

#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse_DEFAULT NULL

#define com_daml_ledger_api_v2_interactive_MinLedgerTime_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (time,min_ledger_time_abs,min_ledger_time_abs),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (time,min_ledger_time_rel,min_ledger_time_rel),   2)
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_time_min_ledger_time_abs_MSGTYPE google_protobuf_Timestamp
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_time_min_ledger_time_rel_MSGTYPE google_protobuf_Duration

#define com_daml_ledger_api_v2_interactive_PreparedTransaction_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  transaction,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          2)
#define com_daml_ledger_api_v2_interactive_PreparedTransaction_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_PreparedTransaction_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_PreparedTransaction_transaction_MSGTYPE com_daml_ledger_api_v2_interactive_DamlTransaction
#define com_daml_ledger_api_v2_interactive_PreparedTransaction_metadata_MSGTYPE com_daml_ledger_api_v2_interactive_Metadata

#define com_daml_ledger_api_v2_interactive_Metadata_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  submitter_info,    2) \
X(a, STATIC,   SINGULAR, STRING,   synchronizer_id,   3) \
X(a, STATIC,   SINGULAR, UINT32,   mediator_group,    4) \
X(a, STATIC,   SINGULAR, STRING,   transaction_uuid,   5) \
X(a, STATIC,   SINGULAR, UINT64,   submission_time,   6) \
X(a, CALLBACK, REPEATED, MESSAGE,  input_contracts,   7) \
X(a, CALLBACK, REPEATED, MESSAGE,  global_key_mapping,   8) \
X(a, STATIC,   OPTIONAL, UINT64,   min_ledger_effective_time,   9) \
X(a, STATIC,   OPTIONAL, UINT64,   max_ledger_effective_time,  10)
#define com_daml_ledger_api_v2_interactive_Metadata_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_interactive_Metadata_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_Metadata_submitter_info_MSGTYPE com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo
#define com_daml_ledger_api_v2_interactive_Metadata_input_contracts_MSGTYPE com_daml_ledger_api_v2_interactive_Metadata_InputContract
#define com_daml_ledger_api_v2_interactive_Metadata_global_key_mapping_MSGTYPE com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry

#define com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   act_as,            1) \
X(a, STATIC,   SINGULAR, STRING,   command_id,        2)
#define com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_DEFAULT NULL

#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_key_MSGTYPE com_daml_ledger_api_v2_interactive_GlobalKey
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_value_MSGTYPE com_daml_ledger_api_v2_Value

#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contract,v1,v1),   1) \
X(a, STATIC,   SINGULAR, UINT64,   created_at,      1000) \
X(a, STATIC,   SINGULAR, BYTES,    driver_metadata, 1001)
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_contract_v1_MSGTYPE com_daml_ledger_api_v2_interactive_transaction_v1_Create

#define com_daml_ledger_api_v2_interactive_DamlTransaction_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   version,           1) \
X(a, CALLBACK, REPEATED, STRING,   roots,             2) \
X(a, CALLBACK, REPEATED, MESSAGE,  nodes,             3) \
X(a, CALLBACK, REPEATED, MESSAGE,  node_seeds,        4)
#define com_daml_ledger_api_v2_interactive_DamlTransaction_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_interactive_DamlTransaction_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_DamlTransaction_nodes_MSGTYPE com_daml_ledger_api_v2_interactive_DamlTransaction_Node
#define com_daml_ledger_api_v2_interactive_DamlTransaction_node_seeds_MSGTYPE com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed

#define com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    node_id,           1) \
X(a, STATIC,   SINGULAR, BYTES,    seed,              2)
#define com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_DEFAULT NULL

#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (versioned_node,v1,v1), 1000)
#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_versioned_node_v1_MSGTYPE com_daml_ledger_api_v2_interactive_transaction_v1_Node

#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   parties,           1) \
X(a, STATIC,   SINGULAR, STRING,   package_name,      2) \
X(a, STATIC,   SINGULAR, STRING,   synchronizer_id,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vetting_valid_at,   4)
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_CALLBACK pb_default_field_callback
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_vetting_valid_at_MSGTYPE google_protobuf_Timestamp

#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  package_preference,   1)
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_package_preference_MSGTYPE com_daml_ledger_api_v2_interactive_PackagePreference

#define com_daml_ledger_api_v2_interactive_PackagePreference_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  package_reference,   1) \
X(a, STATIC,   SINGULAR, STRING,   synchronizer_id,   2)
#define com_daml_ledger_api_v2_interactive_PackagePreference_CALLBACK NULL
#define com_daml_ledger_api_v2_interactive_PackagePreference_DEFAULT NULL
#define com_daml_ledger_api_v2_interactive_PackagePreference_package_reference_MSGTYPE com_daml_ledger_api_v2_PackageReference

extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_Signature_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_SinglePartySignatures_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_PartySignatures_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_MinLedgerTime_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_PreparedTransaction_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_Metadata_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_Metadata_InputContract_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DamlTransaction_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_DamlTransaction_Node_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_msg;
extern const pb_msgdesc_t com_daml_ledger_api_v2_interactive_PackagePreference_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_fields &com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_msg
#define com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_fields &com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_msg
#define com_daml_ledger_api_v2_interactive_Signature_fields &com_daml_ledger_api_v2_interactive_Signature_msg
#define com_daml_ledger_api_v2_interactive_SinglePartySignatures_fields &com_daml_ledger_api_v2_interactive_SinglePartySignatures_msg
#define com_daml_ledger_api_v2_interactive_PartySignatures_fields &com_daml_ledger_api_v2_interactive_PartySignatures_msg
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_fields &com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_msg
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse_fields &com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse_msg
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_fields &com_daml_ledger_api_v2_interactive_MinLedgerTime_msg
#define com_daml_ledger_api_v2_interactive_PreparedTransaction_fields &com_daml_ledger_api_v2_interactive_PreparedTransaction_msg
#define com_daml_ledger_api_v2_interactive_Metadata_fields &com_daml_ledger_api_v2_interactive_Metadata_msg
#define com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_fields &com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_msg
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_fields &com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_msg
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_fields &com_daml_ledger_api_v2_interactive_Metadata_InputContract_msg
#define com_daml_ledger_api_v2_interactive_DamlTransaction_fields &com_daml_ledger_api_v2_interactive_DamlTransaction_msg
#define com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_fields &com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_msg
#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_fields &com_daml_ledger_api_v2_interactive_DamlTransaction_Node_msg
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_fields &com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_msg
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_fields &com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_msg
#define com_daml_ledger_api_v2_interactive_PackagePreference_fields &com_daml_ledger_api_v2_interactive_PackagePreference_msg

/* Maximum encoded size of messages (where known) */
/* com_daml_ledger_api_v2_interactive_PrepareSubmissionRequest_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_PrepareSubmissionResponse_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_SinglePartySignatures_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_PartySignatures_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_ExecuteSubmissionRequest_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_PreparedTransaction_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_Metadata_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_Metadata_SubmitterInfo_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_DamlTransaction_size depends on runtime parameters */
/* com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionRequest_size depends on runtime parameters */
#define com_daml_ledger_api_v2_interactive_DamlTransaction_NodeSeed_size 1038
#define com_daml_ledger_api_v2_interactive_ExecuteSubmissionResponse_size 0
#define com_daml_ledger_api_v2_interactive_GetPreferredPackageVersionResponse_size 4110
#define com_daml_ledger_api_v2_interactive_MinLedgerTime_size 24
#define com_daml_ledger_api_v2_interactive_PackagePreference_size 4107
#define com_daml_ledger_api_v2_interactive_Signature_size 2058
#if defined(com_daml_ledger_api_v2_interactive_GlobalKey_size) && defined(com_daml_ledger_api_v2_Value_size)
#define com_daml_ledger_api_v2_interactive_Metadata_GlobalKeyMappingEntry_size (12 + com_daml_ledger_api_v2_interactive_GlobalKey_size + com_daml_ledger_api_v2_Value_size)
#endif
#if defined(com_daml_ledger_api_v2_interactive_transaction_v1_Create_size)
#define com_daml_ledger_api_v2_interactive_Metadata_InputContract_size (1046 + com_daml_ledger_api_v2_interactive_transaction_v1_Create_size)
#endif
#if defined(com_daml_ledger_api_v2_interactive_transaction_v1_Node_size)
#define com_daml_ledger_api_v2_interactive_DamlTransaction_Node_size (1033 + com_daml_ledger_api_v2_interactive_transaction_v1_Node_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
